### PR TITLE
Fix creation of processed files for frontend pages

### LINKED ISSUE #284: No processed files are generated (backend and frontend)
**Bug description**

If an image is added inside the backend editor, after saving the element, the generated html looks like this:

**CKEditor**
``````

But from my understanding, the src-attribute should be something like this instead:
```src="/fileadmin/_processed_/7/c/csm_myorgimage_21d544ce31.jpg"```

Because the src is not a link to a processed image, the rendering in the frontend does not use a processed image either. The same content rendered in the frontend looks like this:

**Frontend**
``````

In `netresearch/rte-ckeditor-image/Classes/Controller/ImageRenderingController.php` in line 81 there is the following condition

```if ($imageSource !== $systemImage->getPublicUrl()) {}```

Because $imageSource  and $systemImage->getPublicUrl() are both /fileadmin/user_upload/myorgimage.jpg, we will never get a processed image here.

We took a look into `netresearch/rte-ckeditor-image/Resources/Public/JavaScript/Plugins/typo3image.js` and found this code

```
$.extend(filteredAttr, {
    src: urlToRelative(getImg.url),
    width: getImg.processed.width || getImg.width,
    height: getImg.processed.height || getImg.height,
    fileUid: img.uid,
    fileTable: table
});
```
If we change `src: urlToRelative(getImg.url),` to `src: urlToRelative(getImg.processed.url),`, at least the image will be saved as a processed file (getImg.processed contains all the data of the correct processed file) in the Ckeditor. I do not know what other side effects this will trigger... This also creates a processed file in the frontend.

**Steps to reproduce**
To reproduce the problem:

- add a image inside the backend editor, set an individual size (smaller then the original) and save
- look at the generated source code inside the editor and check if the image path links to a fileadmin/_processed image or to the original, not processed file
- open the same page in the frontend and look at the path of the image and check if it links to a fileadmin/_processed image

**Expected behavior**
If a image is added in the Ckeditor and an individual size (smaller then the original) is set, the image should be processed and an image with the new size should be created inside fileadmin/_processed

**Environment**
 - TYPO3 version:  v12.4.14
 - PHP version: php 8.1, php 8.2, php 8.3
 - Extension version: v12.0.1

**Documentation**
Have you checked the readme/documentation?
- [X ] Yes, but I couldn't find anything helpful

### PR DESCRIPTION
**Pull request by bigahuna**
Fixes #284 and #286 

The current version of rte_ckeditor_image (tested up to 12.0.2) does not create processed files inside `fileadmin/_processed_` anymore (frontend and backend).

The reason is a comparison inside ImageRenderingcontroller (`if ($imageSource !== $systemImage->getPublicUrl())`).

But imageService and $systemImage->getPublicUrl() always point to the original file and never to the processed file and are therefore always the same.

This PR adds code that always tries to create a processed file and then proceeds inside the if block from above. This results in the creation of images inside `fileadmin/_processed_` as expected.

This was tested with normal TYPO3 text and text/image plugins and also with custom extensions that use the CKeditor for text and image input. In the frontend templates one has to use `<f:format.html>{ckeditorcontent}</f:format.html>` to use processing.

### CODE REVIEW

File: Classes/Controller/ImageRenderingController.php [hunk 1]
```diff
@@ -78,16 +79,19 @@ public function renderImageAttributes(?string $content, array $conf = []): strin
                     $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
                     $systemImage     = $resourceFactory->getFileObject($fileUid);
 
-                    if ($imageSource !== $systemImage->getPublicUrl()) {
-                        // Source file is a processed image
+                    // check if there is a processed variant, if not, create one
+                    $processedFile = null;
+                    if ($systemImage instanceof File) {
```
Comment (CybotTM) [inline Classes/Controller/ImageRenderingController.php:85]: This check seems superfluous to me, `getFileObject()` always returns `File`, otherwise it would throw an exception.

https://api.typo3.org/11.5/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_resource_1_1_resource_factory.html#aa11578c4934a73ea7239af6e5e788bc8

File: Classes/Utils/ProcessedFilesHandler.php [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+     *   $imageConfiguration = [
+     *     'width' => '200c',
+     *     'height' => '200c',
+     *   ];
+     *
+     * @param File $file The file object
+     * @param array $imageConfiguration The image configuration
+     * @return ProcessedFile|bool
+     */
+    public function createProcessedFile(File $file, array $imageConfiguration): ProcessedFile|bool
```
Comment (CybotTM) [inline Classes/Utils/ProcessedFilesHandler.php:27]: This method should always return `File`, in case of error it should throw an `exception`

File: Classes/Controller/ImageRenderingController.php [hunk 3]
```diff
@@ -78,16 +79,19 @@ public function renderImageAttributes(?string $content, array $conf = []): strin
...
                             'width'  => (int) ($imageAttributes['width']  ?? $systemImage->getProperty('width') ?? 0),
                             'height' => (int) ($imageAttributes['height'] ?? $systemImage->getProperty('height') ?? 0),
                         ];
+                        $processedFile = $checkProcessed->createProcessedFile($systemImage, $imageConfiguration);
+                    }
 
-                        $processedFile = $this->getMagicImageService()
-                            ->createMagicImage($systemImage, $imageConfiguration);
-
+                    if ($processedFile !== false) {
```
Comment (CybotTM) [inline Classes/Controller/ImageRenderingController.php]: `$processedFile` may be `null` (see line 83) and this will evaluate to `true` if `$processedFile` is `null`

**Review by CybotTM — CHANGES_REQUESTED** [review]
Hi @bigahuna,

thanks for your PR, please see my comments.

File: Classes/Controller/ImageRenderingController.php (hunk 1 above)
Comment (bigahuna) [reply Classes/Controller/ImageRenderingController.php:85]: yes, you are right, I will fix it

Comment (bigahuna) [reply Classes/Controller/ImageRenderingController.php]: done

File: Classes/Controller/ImageRenderingController.php (hunk 3 above)
Comment (bigahuna) [reply Classes/Controller/ImageRenderingController.php]: done

**Review by CybotTM — APPROVED** [review]

**Comment by bigahuna** [comment]
I added another commit to this PR that hopefully fixes #286

**Comment by Gitsko** [comment]
hi @bigahuna , i just wanted to test the customization, but unfortunately the images from fileadmin still appear directly and are not used from the _processed_ folder. Do you have any idea if something is missing?

**Comment by bigahuna** [comment]
> hi @bigahuna , i just wanted to test the customization, but unfortunately the images from fileadmin still appear directly and are not used from the _processed_ folder. Do you have any idea if something is missing?

Do you relate to the frontend or the images inside CKeditor?

The last commit related to #286 makes sure that images that already point to a processed file that got deleted (maintenance task -> Scan / delete temporary images) are recreated with their original size instead of a maxWidth of 300px after hitting save inside CKeditor.

Example: In the source code view of CKeditor is a link to a processed file like this:

```
<img class="" src="/fileadmin/_processed_/2/d/myimage2_b1e768fa39.png" data-htmlarea-file-uid="434" data-htmlarea-file-table="sys_file" width="1000" height="907" title="" alt="" data-title-override="true" data-alt-override="true">
```

Now 
- delete this temporary file `/fileadmin/_processed_/2/d/myimage2_b1e768fa39.png` 
- open the CKeditor-contentelement where this file is included and hit save 
- the file will be recreated but with a maxWidth of 300px

300px is the default maxWidth inside typo3/cms-core/Classes/Resource/Service/MagicImageService.php. This happens because we pass non existing parameters to `$magicImageService->setMagicImageMaximumDimensions`. This is now fixed and the maxWidth is whatever you configure inside tsconfig `RTE.default.buttons.image.options.magic.maxWidth = 1000`

If you already have links to the original files in CKeditor like this, they will no be changed to processed files:

```
<img class="" src="/fileadmin/user_upload/myimage1.png" data-htmlarea-file-uid="318" data-htmlarea-file-table="sys_file" width="700" height="358" title="" alt="Automotive Sensor Interfaces" data-title-override="true" data-alt-override="true">
```

I did not search for the reason why new files are not saved as processed files inside CKeditor because there is nothing bad happening here as far as I can see. In the frontend, this files will be created as processed files with the correct dimensions, no matter if the backend link in CKeditor points to a processed file or the original file. This certainly has to do something with the Update to CKEditor 5 in TYPO3 12, but I did no have the time to dig deeper.

Summary: This PR fixes two things:

- recreate processed files with the correct dimensions instead of a maxWidth of 300 inside the CKeditor after removal of temporary files
- fix recreation of processed files for frontend pages after removal of temporary files instead of doing nothing and linking to non existing files inside `fileadmin/_processed_`

**Comment by bigahuna** [comment]
> hi @bigahuna , i just wanted to test the customization, but unfortunately the images from fileadmin still appear directly and are not used from the _processed_ folder. Do you have any idea if something is missing?

Sorry, another thing to consider: If you include the Typoscript set in the template settings before fluid_styled_content, it does not work at all. It works fine if you include it after fluid_styled_content. 

I do not know if this has something to do with TYPO3 v12, but the lib.parseFunc_RTE.tags.img.preUserFunc defined in rte-ckeditor-image/Configuration/TypoScript/ImageRendering/setup.typoscript only works if included after fluid_styled_content

typoscript

Please try to change the order of the extension in the template and check if the processed files are now created in the frontend.

**Review by Gitsko — APPROVED** [review]

**Comment by Gitsko** [comment]
hi @bigahuna , thank you very much for your detailed explanations and for your commitment, it was actually the static template setting for me.

From my point of view, the MR now fits, I will merge it.

**Review by Gitsko — COMMENTED** [review]
- [x] works

**Comment by iamwebrocker** [comment]
> Sorry, another thing to consider: If you include the Typoscript set in the template settings before fluid_styled_content, it does not work at all. It works fine if you include it after fluid_styled_content.

Sorry for chiming in here; what is the supposed correct order for the TS inclusion for v12? 

Before or After fluid_styled_content?
I am confused because in another issue the "fix" is to make sure that the TS is before FSC: https://github.com/netresearch/t3x-rte_ckeditor_image/issues/304#issuecomment-2590263063

Here now it is after FSC. 🧐
