### PR TITLE
[BUGFIX] Fixes #254: handle deleted files

### LINKED ISSUE #254: Exception thrown when element has deleted file references
**Bug description**
When a element (e.g. tt_content) with a RTE is opened in the BE a exception is thrown.

**Steps to reproduce**
To reproduce the problem:

1. Create a text element and link to a file in the RTE.
2. Delete said file
3. Open the text element in the BE

**Expected behavior**
The RTE renders normal and the missing image is simply excluded.

**Screenshots or logs**
TYPO3\CMS\Core\Resource\Exception\FileDoesNotExistException, code #1317178604, file /var/www/htdocs/typo3/sysext/core/Classes/Resource/ResourceFactory.php, line 223: No file found for given UID: xxx

This error occurs since version 11.0.14 and was introduced with the changes for #199 

**Environment**
 - TYPO3 version: 11.5.32
 - PHP version: 8.0
 - Extension version: 11.0.14

**Documentation**
Have you checked the readme/documentation?
- [x] Yes, but I couldn't find anything helpful

### PR DESCRIPTION
**Pull request by hannesbochmann**
This change simply catches the exception TYPO3 may throw when trying to retrieve a already deleted file.

fixes #254

### CODE REVIEW

**Review by Gitsko — APPROVED** [review]

File: Classes/Database/RteImagesDbHook.php [hunk 1]
```diff
@@ -182,8 +182,12 @@ protected function getProcessedFile(array $attribArray): string
 
         $siteUrl  = GeneralUtility::getIndpEnv('TYPO3_SITE_URL');
 
-        $originalImageFile = $resourceFactory
-            ->getFileObject((int)$attribArray['data-htmlarea-file-uid']);
+        try {
+            $originalImageFile = $resourceFactory
+                ->getFileObject((int)$attribArray['data-htmlarea-file-uid']);
+        } catch (\Exception $e) {
+            return '';
```
Comment (Gitsko) [inline Classes/Database/RteImagesDbHook.php:189]: `$this->logger->error($message, ['exception' => $e]);`

**Review by Gitsko — COMMENTED** [review]
Better to add a logger also

**Review by Gitsko — APPROVED** [review]
